### ISSUE TITLE
Nano-simcard orientation

### ISSUE THREAD

**Issue by jirikrepl** [pycom/pycom-documentation#103]
Hi,
I tried to find how to insert nano-simcard into FiPy in the docs, but it wasn't probably still included.

People were already talking about it here, maybe we could include it in docs https://forum.pycom.io/topic/2486/nano-sim-card-orentation/2

**Comment by sdaniel55** [comment]
@jirikrepl it's right here: https://docs.pycom.io/gettingstarted/connection/fipy#sim-card

**Comment by jirikrepl** [comment]
OK. I was looking at datasheet PDF and this section: https://docs.pycom.io/datasheets/development/fipy

I am not sure but it seems to be that the structure of chapters could be improved a bit.

Maybe there can be just one subchapter about every development module and everything including this datasheets can be added there.

**Comment by sdaniel55** [comment]
@jirikrepl We could add that image to the datasheet as well. I'll add it to the list. I'll do some research on how could we improve the structure.
