### ISSUE TITLE
[Expansion board 3.0] Wrong values for battery voltage divider resistors in docs

### ISSUE THREAD

**Issue by cyberman54** [pycom/pycom-documentation#106]
Documentation says 115kOhm/56kOhm on overview page, but 1MOhm/1MOhm on details page (pdf).
Don't know what's correct here, i assume 115/56 is from expansion board 2.0, so 1M/1M could be new value for expansion board 3.0?

**Comment by gijsio** [comment]
Thanks! Added to the documentation
