### ISSUE TITLE
Coping Python code results in copying of unprintable characters

### ISSUE THREAD

**Issue by jirikrepl** [pycom/pycom-documentation#116]
## What are the steps to reproduce this issue?
1. go to this page https://docs.pycom.io/tutorials/all/mqtt
2. copy mqtt example by selecting the code from the web page (not pressing the copy button)
3. upload this code to a device and restart the device

## What happens?
The device fails to execute the code at line 5, then on line 9 and so on.

There are unprintable characters on line 5 and 9 rendered with HTML with Gitbook.
These unprintable characters aren't visible in Atom but might be visible in other IDEs or editors.

Furthermore, the copy button is too small and has low contrast.

<img width="1552" alt="screen shot 2018-11-09 at 12 28 22" src="https://user-images.githubusercontent.com/2588479/48260304-3e94f700-e41b-11e8-8c40-be85948f9b80.png">

![screen shot 2018-11-09 at 12 28 58](https://user-images.githubusercontent.com/2588479/48260312-43f24180-e41b-11e8-8da8-b8db90b64194.png)

**Comment by sdaniel55** [comment]
@jirikrepl I've reported this to GitBook, they know about it and working on a fix. This is their latest response:

> "We have not found a correct way to fix the copy/paste issue yet. It may look like an obvious thing to fix, but we use these special characters for compatibility purposes, and we have not found a perfect solution yet."

**Comment by jirikrepl** [comment]
Thank you 👍
