### ISSUE TITLE
issue while installing pymakr on visual studio

### ISSUE THREAD

**Issue by vijayprakash1** [pycom/pycom-documentation#134]
There was an error with your serial port module, Pymakr will likely not work properly. Please try to install again or report an issue on our GitHub (see developer console for details)

**Comment by Thyno** [comment]
Hello,
I have the same, I think it's a problem of compatibility with vscode 1.39
I saw that: 
1.1.3 - Compatibility vscode 1.36
Windows64 and mac compatibility with vscode 1.36 (serialport compile to match electron version)
Double pymakr terminal issue solved (#47)
Spelling mistake (#52)
Added help text for auto_connect

?????
Thyno
