### ISSUE TITLE
Add expansion board schematics

### ISSUE THREAD

**Issue by r-uhlig** [pycom/pycom-documentation#2]
### Add the expansion board schematics
https://github.com/pycom/pycom-documentation/blob/master/chapter/datasheets/boards/expansion.md

The schematics are needed by developers to correctly use the hardware.

**Comment by Bucknalla** [comment]
Hi @r-uhlig we do not provide the schematics for the expansion board but you can find the pinout documentation, which should be all that you need to program your device.

Here's a link to the pinout document - https://docs.pycom.io/chapter/datasheets/boards/expansion.html
