### ISSUE TITLE
ticks_diff() Argument order is incorrect

### ISSUE THREAD

**Issue by DG12** [pycom/pycom-documentation#253]
As mentioned by robert-hh Mar 3, 2019, 4:53 AM  in [https://forum.pycom.io/topic/4472/argument-order-of-time-ticks_diff](https://forum.pycom.io/topic/4472/argument-order-of-time-ticks_diff)

- "since Nov 8, 2018. The argument order has been swapped. it is now time.ticks_diff(new, old). That is good and bad.
Good, in that it matches what the uasyncio library expects and
Good in that it is now compatible with the micropython.org branch.
Bad, since existing code for the Pycom devices which make use of this call now breaks."

For example:

> start = time.ticks_us()
> time.ticks_diff(start, time.ticks_us())
>  -7646164

Please revise [https://docs.pycom.io/firmwareapi/micropython/utime/](https://docs.pycom.io/firmwareapi/micropython/utime/) accordingly

**Comment by gijsio** [comment]
Hi,
I merged your changes to the documentation! Thanks
Gijs
