### ISSUE TITLE
LoPy Pinout 'PMW->PWM'

### ISSUE THREAD

**Issue by nevercast** [pycom/pycom-documentation#30]
[Documentation Page](https://docs.pycom.io/chapter/datasheets/development/lopy.html)
[PDF Pinout](https://docs.pycom.io/chapter/datasheets/downloads/lopy-pinout.pdf)

**Comment by sdaniel55** [comment]
Hi @nevercast, I believe this issue has been resolved

**Comment by nevercast** [comment]
That does seem to be the case, thank you.

**Comment by nevercast** [comment]
The PDF has been updated, the screenshot needs updating. https://docs.pycom.io/img/lopy-pinout.png.
