### ISSUE TITLE
The SD function example use a non-existent function!!!

### ISSUE THREAD

**Issue by gartek** [pycom/pycom-documentation#340]
(Hi! 👋  Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

## What are the steps to reproduce this issue?
1. Executing the SD example code.

## What happens?
the example code in SD uses a function for read files "f.readall()" that function doesn't exist and the micropython gets an error.

## Any logs, error output, etc?
*(If it’s long, please paste to https://gist.github.com and insert the link here)*

## What versions of software are you using?
- **Board type and hardware version: FiPy**
- **`os.uname()` output: (sysname='FiPy', nodename='FiPy', release='1.20.2.r1', version='v1.11-a5aa0b8 on 2020-09-09', machine='FiPy with ESP32', lorawan='1.0.2', sigfox='1.0.1', pybytes='1.6.0')**
- **Atom/VSCode version:**
- **Pymakr version:1.1.7**
- **Operating system: Linux**

**Comment by pycommatthew** [comment]
I have fixed this and changed the example to `.read()`
