### ISSUE TITLE
Correction to pinout in PySense2X_specsheet.pdf version 1.0

### ISSUE THREAD

**Issue by jandleuven** [pycom/pycom-documentation#356]
I think the pinout for the 'J4' external IO Header in the PySense2X_specsheet.pdf (version 1.0) is not correct. It is basically the numbering of the pins of the 10-pin header that is wrong. And the pinout lacks information about which pins of the pycom module  the 10-pin header is connected to. I made corrections on the following exert from the specsheet:

![Pysense2X_corrected_pinout](https://user-images.githubusercontent.com/76472156/102869096-67ca4300-443b-11eb-84c3-59fad1253422.jpg)

**Comment by peter-pycom** [comment]
@jandleuven thanks for this! I haven't checked the details of your proposal, but I have noticed that indeed something is not correct here in our documentation. Are you blocked by this?

Otherwise, @gijsio can you put this on your list?

**Comment by jandleuven** [comment]
Dear Peter,

Thanks. I am not blocked.  I think I figured out what the correct pinout is, and that is working for me.  But it would be good that you specialists confirm that what I propose is the correct pinout.  And that it is corrected in the documentation so others don’t lose time with this.

Best regards,
Jan

**Comment by gijsio** [comment]
Thanks, I'll make sure the figure gets updated!
