### ISSUE TITLE
Add WiPy 2.0 schematics

### ISSUE THREAD

**Issue by r-uhlig** [pycom/pycom-documentation#4]
The schematics are necessary for some developers to correctly use the WiPy.

**Comment by Bucknalla** [comment]
Hi @r-uhlig we do not provide the schematics for the WiPy 2.0 but you can find the pinout documentation, which should be all that you need to program your device.

Here's a link to the pinout document - https://docs.pycom.io/chapter/datasheets/development/wipy2.html
