### ISSUE TITLE
GPy Documentation seriously garbled

### ISSUE THREAD

**Issue by DG12** [pycom/pycom-documentation#492]
Just look at.  [https://docs-mk2.readthedocs.io/en/latest/gettingstarted/connection/gpy/](https://docs-mk2.readthedocs.io/en/latest/gettingstarted/connection/gpy/)

## What happens?
See formatting info like: {% tabs %} {% tab title=“Exp Board 2.0” %} * 
Many PNG images missing for example 
https://docs-mk2.readthedocs.io/en/latest/gettingstarted/connection/gpy/.gitbook/assets/baregpy.png
## What were you expecting to happen?

finished documentation

**Comment by jakobrosenberg** [comment]
Hi @DG12, great catch. I've forwarded your issue and hopefully this should be resolved shortly.

**Comment by jakobrosenberg** [comment]
Just a quick follow up. I'm still waiting to hear if we maintain the docs at readthedocs.io.

In the meantime, you can see our official documentation here: https://docs.pycom.io/

**Comment by Xykon** [comment]
I can confirm these docs are not maintained by Pycom. Unfortunately we have no control over the content. Please only use our official documentation. Thanks
