### ISSUE TITLE
coding_rate response values seem to be wrong. 

### ISSUE THREAD

**Issue by tw-maelstrom** [pycom/pycom-documentation#5]
While trouble shooting an [issue with my LoPy](https://forum.pycom.io/topic/1795/lora-receiving-data-intermittently/14) it looks I uncovered a discrepancy between docs and implementation for `coding_rate`. 

[modlora.c ](https://github.com/pycom/pycom-micropython-sigfox/blob/master/esp32/mods/modlora.c#L163) shows: 
```
typedef enum {
    E_LORA_CODING_4_5 = 1,
    E_LORA_CODING_4_6 = 2,
    E_LORA_CODING_4_7 = 3,
    E_LORA_CODING_4_8 = 4
} lora_coding_rate_t;
```

While [docs](https://github.com/pycom/pycom-documentation/blame/master/chapter/firmwareapi/pycom/network/lora.md#L179) indicate:

*`lora.coding_rate([coding_rate])` Get or set the coding rate in raw LoRa mode (LoRa.LORA). The allowed values are: `LoRa.CODING_4_5 (0), LoRa.CODING_4_6 (1), LoRa.CODING_4_7 (2) and LoRa.CODING_4_8 (3)`.*

I *think* this is just a documentation issue as setting the coding rate to `0` on the sx1272 would put it in FSK mode.

**Comment by ep1cman** [comment]
Fixed by d1c24a005caf8db84a147edbdb5ff23c1d795408
