### ISSUE TITLE
'from network import lora' source codes

### ISSUE THREAD

**Issue by AlexanderGros** [pycom/pycom-documentation#510]
Hello,

I would like to find more infos about the lora.stat part.
Cannot find the 'network' files from: 'from network import lora'  in the pycom repositories ?
Nor the pycom firmwareapi codes such as in:
https://docs.pycom.io/firmwareapi/pycom/network/lora/

Thanks

**Comment by Xykon** [comment]
https://github.com/pycom/pycom-micropython-sigfox/blob/a37510c092bcec00671c924accb97dcdfa2f4b5d/esp32/mods/modlora.c#L2205
