### ISSUE TITLE
Note differences between exp board 2.0 and 3.0 in Pymakr section

### ISSUE THREAD

**Issue by ShawnHymel** [pycom/pycom-documentation#55]
I am using a LoPy4 with an Expansion Board 3.0.

 * Section 1.2.3 (Atom), under "Connecting via Serial USB," you mention that you need to "remove the wire between GND and G23." This step does not need to be performed on an exp board 3.0.

**Comment by danicampora** [comment]
Hello Hymel,

Thanks for reporting this. We will fix it right away.

Cheers,
Daniel
