### ISSUE TITLE
can not update firmware

### ISSUE THREAD

**Issue by mjmillere80** [pycom/pycom-documentation#96]
We have a few W01 modules. We are trying to implement them in a new design but we are unable to update the firmware. I have grounded p2 (pin5) then momentarily grounded the reset pin but the W01 will not enter bootloader mode. By watching the REPL it appears to reset but then boots normally regardless of the grounding of p2. Am I missing something here?

**Comment by Xykon** [comment]
Do you have anything connected to P8? If P8 is high at boot time, the state of P2 is ignored and the module will not go into update mode.

**Comment by mjmillere80** [comment]
Thank you for the quick response.
I will check on this and get back to you as soon as I can.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by mjmillere80** [comment]
Grounded P8... No change except that it fails without trying to retrieve the new file it immediately fails and asks me to check connections. Before P8 was grounded it timed out and failed.

**Comment by Xykon** [comment]
What kind of output do you get on the serial port?

If the module is in firmware update mode it should say "Waiting for download" as the last message after reset. Then you should be able to connect with the firmware update tool.

**Comment by mjmillere80** [comment]
rst:0x1 (POWERON_RESET),boot:0x32 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0x00
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:QIO, clock div:1
load:0x3fff0008,len:4
load:0x3fff000c,len:148
load:0x40078000,len:11876
ho 0 tail 12 room 4
load:0x40080000,len:268
entry 0x40080034
MicroPython v1.8.6-621-g17ee404e on 2017-05-25; WiPy with ESP32
Type "help()" for more information.
>>>

**Comment by mjmillere80** [comment]
Sorry I still had Atom up the last time I tried this. I stopped atom and ran the firmware updater again. Now I have a different error. I am updating from a file to 1.17.0.b1. Now I am getting **"Failed to connect to ESP32: Invalid head of packet (U)"**.

**Comment by mjmillere80** [comment]
Sorry I still had Atom up the last time I tried this. I stopped atom and ran the firmware updater again. Now I have a different error. I am updating from a file to 1.17.0.b1. Now I am getting "Failed to connect to ESP32: Invalid head of packet (\x08)". I have used this firmware file on hundreds of WiPy 3.0's with no problem.



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Xykon** [comment]
As long as you don't get the "waiting for download" message on reset but the MicroPython prompt, you will not be able to connect with the firmware updater. Are you able to capture the state of P2 and P8 during reset with an Oscilloscope? P2 must be low and P8 must not be high.

It might be worth double-checking that you're using the correct pins: https://docs.pycom.io/chapter/datasheets/downloads/w01-pinout.pdf

**Comment by mjmillere80** [comment]
I have by means of wire and solder grounded both pins for the update.
A scope is available if needed however.
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by mjmillere80** [comment]
After insuring P8 was low, it was high and re-soldering the wire on P2 it worked as advertised thank you. I consider this closed.
